// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo2okVcAcedbMp5SVdoy1RazWp7OwJmQ4',
    appId: '1:851829128922:web:4128c7254eabe8abfe6fe3',
    messagingSenderId: '851829128922',
    projectId: 'body-report-d9396',
    authDomain: 'body-report-d9396.firebaseapp.com',
    storageBucket: 'body-report-d9396.firebasestorage.app',
    measurementId: 'G-52K4373LZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJF5AJVYHXgSlCifH6YlArNhzz3_RBbfE',
    appId: '1:851829128922:android:aeebcf8377ec2601fe6fe3',
    messagingSenderId: '851829128922',
    projectId: 'body-report-d9396',
    storageBucket: 'body-report-d9396.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBloshWPSP6DcyPyJ2WW7d32hXtHksmDRU',
    appId: '1:851829128922:ios:0c04b43744b61499fe6fe3',
    messagingSenderId: '851829128922',
    projectId: 'body-report-d9396',
    storageBucket: 'body-report-d9396.firebasestorage.app',
    iosBundleId: 'com.example.bodyCheckup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBloshWPSP6DcyPyJ2WW7d32hXtHksmDRU',
    appId: '1:851829128922:ios:0c04b43744b61499fe6fe3',
    messagingSenderId: '851829128922',
    projectId: 'body-report-d9396',
    storageBucket: 'body-report-d9396.firebasestorage.app',
    iosBundleId: 'com.example.bodyCheckup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo2okVcAcedbMp5SVdoy1RazWp7OwJmQ4',
    appId: '1:851829128922:web:201fc92059db2e54fe6fe3',
    messagingSenderId: '851829128922',
    projectId: 'body-report-d9396',
    authDomain: 'body-report-d9396.firebaseapp.com',
    storageBucket: 'body-report-d9396.firebasestorage.app',
    measurementId: 'G-ZFNJS5FV8J',
  );
}
